version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    restart: unless-stopped
  api:
    container_name: 'api'
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 7000:7000
    stdin_open: true
    tty: true